# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from model.group import Group

from fixture.application import  Application



def test_add_group(app):
  old_groups = app.group.get_group_list()
  group = Group(groupname="sdfsdываываывf", groupheader="sdfsdf",  groupfooter="sdf")
  app.group.create_groups(group)
  assert len(old_groups) + 1 == app.group.count()
  new_groups = app.group.get_group_list()
  old_groups.append(group)
  assert sorted(old_groups, key = Group.id_or_max) == sorted(new_groups, key = Group.id_or_max)


def test_add_empty_group(app):
  old_groups = app.group.get_group_list()
  group = Group(groupname="sdfsdываываывf", groupheader="sdfsdf", groupfooter="sdf")
  app.group.create_groups(group)
  new_groups = app.group.get_group_list()
  assert len(old_groups) + 1 == len(new_groups)
  old_groups.append(group)
  assert sorted(old_groups, key = Group.id_or_max) == sorted(new_groups, key = Group.id_or_max)


