# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from model.group import Group
from fixture.application import  Application



def test_add_group(app):
  app.session.login(user="admin", password="secret")
  app.group.create_groups(Group(groupname="sdfsdываываывf", groupheader="sdfsdf",  groupfooter="sdf"))
  app.group.view_groups()
  app.session.logout()

def test_add_empty_group(app):
  app.session.login(user="admin", password="secret")
  app.group.create_groups(Group(groupname="", groupheader="",  groupfooter=""))
  app.group.view_groups()
  app.session.logout()

