# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFirst():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_first(self):
    # Test name: first
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://addressbook/")
    # 2 | setWindowSize | 1385x949 | 
    self.driver.set_window_size(1385, 949)
    # 3 | type | name=user | admin
    self.driver.find_element(By.NAME, "user").send_keys("admin")
    # 4 | type | name=pass | secret
    self.driver.find_element(By.NAME, "pass").send_keys("secret")
    # 5 | click | css=input:nth-child(7) | 
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()
    # 6 | click | linkText=groups | 
    self.driver.find_element(By.LINK_TEXT, "groups").click()
    # 7 | click | id=content | 
    self.driver.find_element(By.ID, "content").click()
    # 8 | click | name=new | 
    self.driver.find_element(By.NAME, "new").click()
    # 9 | click | name=group_name | 
    self.driver.find_element(By.NAME, "group_name").click()
    # 10 | type | name=group_name | sdfsdf
    self.driver.find_element(By.NAME, "group_name").send_keys("sdfsdf")
    # 11 | click | name=group_header | 
    self.driver.find_element(By.NAME, "group_header").click()
    # 12 | type | name=group_header | sdfsdf
    self.driver.find_element(By.NAME, "group_header").send_keys("sdfsdf")
    # 13 | click | name=group_footer | 
    self.driver.find_element(By.NAME, "group_footer").click()
    # 14 | type | name=group_footer | sdfsdf
    self.driver.find_element(By.NAME, "group_footer").send_keys("sdfsdf")
    # 15 | click | name=submit | 
    self.driver.find_element(By.NAME, "submit").click()
    # 16 | click | linkText=groups | 
    self.driver.find_element(By.LINK_TEXT, "groups").click()
    # 17 | click | css=b | 
    self.driver.find_element(By.CSS_SELECTOR, "b").click()
    # 18 | click | linkText=Logout | 
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
  
