# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test_add_group():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test_add_group(self):
    self.open_home_page()
    self.login()
    self.open_groups_page()
    self.create_groups()
    self.view_groups()
    self.logout()

  def logout(self):
    # logout
    self.driver.find_element(By.LINK_TEXT, "Logout").click()

  def view_groups(self):
    # view group
    self.driver.find_element(By.LINK_TEXT, "groups").click()

  def create_groups(self):
    # init group creation
    self.driver.find_element(By.NAME, "new").click()
    # fill group form
    self.driver.find_element(By.NAME, "group_name").click()
    self.driver.find_element(By.NAME, "group_name").send_keys("sdfsdываываывf")
    self.driver.find_element(By.NAME, "group_header").click()
    self.driver.find_element(By.NAME, "group_header").send_keys("sdfsdf")
    self.driver.find_element(By.NAME, "group_footer").click()
    self.driver.find_element(By.NAME, "group_footer").send_keys("sdf")
    self.driver.find_element(By.NAME, "submit").click()

  def open_groups_page(self):
    # open groups page
    self.driver.find_element(By.LINK_TEXT, "groups").click()

  def login(self):
    # login
    self.driver.find_element(By.NAME, "user").send_keys("admin")
    self.driver.find_element(By.NAME, "pass").send_keys("secret")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()

  def open_home_page(self):
    # open home page
    self.driver.get("http://addressbook/")
  
