# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from group import Group
from application import  Application

@pytest.fixture
def app(request):
  fixture = Application()
  request.addfinalizer(fixture.destroy)
  return fixture

def test_add_group(app):
  app.login(user="admin", password="secret")
  app.create_groups(Group(groupname="sdfsdываываывf", groupheader="sdfsdf",  groupfooter="sdf"))
  app.view_groups()
  app.logout()

def test_add_empty_group(app):
  app.login(user="admin", password="secret")
  app.create_groups(Group(groupname="", groupheader="",  groupfooter=""))
  app.view_groups()
  app.logout()

